#!/bin/sh

ROOT=`pwd`
PUBLIC="$ROOT/../flu-public"

echo "from $ROOT to $PUBLIC"

if [ ! -d "$PUBLIC" ] ; then
  git clone git@github.com:erlyvideo/flussonic.git "$PUBLIC"
else
  (cd "$PUBLIC"; git pull)
fi

git archive master | (cd "$PUBLIC"; tar xv)

LAST_COMMIT_MESSAGE=`git log -n 1 --format="%s"`

cd "$PUBLIC"

git add .
git commit -m "$LAST_COMMIT_MESSAGE"
git push
