#!/usr/bin/env escript

% sublime: syntax Erlang

-mode(compile).
-compile(export_all).

main([]) ->
  io:format("./contrib/migrate_dvr /storage/channel0\n"),
  erlang:halt(1);

main([Path]) ->
  code:add_pathz("apps/flussonic/ebin"),
  code:add_pathz("/opt/flussonic/apps/flussonic/ebin"),
  net_kernel:start(['migrate@127.0.0.1', longnames]),
  case file:read_file("/etc/flussonic/cookie") of
    {ok, Cookie} -> erlang:set_cookie(node(), binary_to_atom(binary:replace(Cookie,<<"\n">>,<<>>), latin1) );
    {error, enoent} -> ok
  end,
  case net_kernel:connect('flussonic@127.0.0.1') of
    true -> ok;
    false ->
      io:format("Failed to connect to running instance of flussonic\n"),
      erlang:halt(2)
  end,
  Pid = proc_lib:spawn_link('flussonic@127.0.0.1', dvr_hour_storage, migrate_from_segments, [Path]),
  erlang:monitor(process, Pid),
  receive {'DOWN', _, _, Pid, _} -> ok end,
  ok.




