#!/bin/bash
### BEGIN INIT INFO
# Provides:          flussonic
# Required-Start:    $local_fs $network $syslog
# Required-Stop:     $local_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop flussonic streaming server
### END INIT INFO

FLUDIR=/opt/flussonic

[ -f /etc/default/flussonic ] && . /etc/default/flussonic

[ -e priv/flussonic.conf ] && CONF=priv/flussonic.conf
[ -e priv/sample/flussonic.conf ] && CONF=priv/sample/flussonic.conf

case $1 in
"start")
  echo -n "Starting flussonic "
  mkdir -p /var/log/flussonic
  mkdir -p /var/run/flussonic
  export RUN_ERL_LOG_GENERATIONS=100
  export RUN_ERL_LOG_MAXSIZE=10000000
  rm -rf /var/run/flussonic/*
  run_erl -daemon /var/run/flussonic/ /var/log/flussonic "exec $0 launch"
  i=0
  while ((i < 100)) && [ ! -f "/var/run/flussonic.pid" ] ; do 
    echo -n "."
    ((i = i+1))
    sleep 1
  done 
  [ -f "/var/run/flussonic.pid" ] && echo "done" || (echo "failed"; exit 1)
  ;;
"stop")
  echo "Stopping flussonic"
  echo -e "init:stop().\n" > /var/run/flussonic/erlang.pipe.1.w
  sleep 1
  kill `cat /var/run/flussonic.pid`
  rm -rf /var/run/flussonic/*
  ;;
"run")
  echo "Running"
  $0 launch
  ;;
"launch")
  [ -e $FLUDIR ] && cd $FLUDIR
  export ERL_LIBS=apps:deps
  export PID_PATH="/var/run/flussonic.pid"
  SBT=""
  # This option is disabled unless Rickard makes +sbt flag non-failable
  # if [ `uname` == "Linux" ]; then
  #   SBT="+sbt s"
  # fi
  CMD="erl +K true +A 16 +a 2048 ${SBT} -name flussonic@127.0.0.1 -pa apps/*/ebin -pa deps/*/ebin -boot start_sasl -s flussonic -sasl errlog_type error"
  exec $CMD
  ;;
"reload")
  echo -e "flu:reconf().\n" > /var/run/flussonic/erlang.pipe.1.w
  ;;
"restart")
  echo "Restarting"
  $0 stop
  $0 start
  ;;
"attach")
  echo "Attaching"
  cd $FLUDIR
  to_erl /var/run/flussonic/
  ;;
"shell")
  echo "Remote shell"
  erl -name debug@127.0.0.1 -remsh flussonic@127.0.0.1
  ;;
"force-reload")
  echo "Force reload"
  $0 stop
  $0 start
  ;;
"status")
  echo "Status unimplemented"
  ;;
*)
  echo "$0 start|stop|run|reload|restart|attach|shell"
esac
