#!/bin/bash

FLUDIR=/opt/flussonic

function copy_binaries {
  cd $FLUDIR
  
  echo "Copy prebuilt binaries"
  find apps -name *.so -delete
  mkdir -p apps/flussonic/priv/
  [ -e apps/flussonic/priv/mmap.so ] || cp -f priv/binaries/linux/mmap.so apps/flussonic/priv/mmap.so
}


copy_binaries

update-rc.d flussonic defaults
